### ISSUE TITLE
No permissions to create composer/ssh directories

### ISSUE THREAD

**Issue by Fulmenef** [origamiphp/docker-images#86]
When using composer in the php 7.4 and 8.1 images, I have this kind of error:
```
fatal: could not create leading directories of '/var/www/.composer/cache/vcs/git-bitbucket.org-myrepository.git'
```

So far I was able to fix it by manually creating the directories /var/www/{.composer,.cache,.ssh} and changing the owner from root to www-data but perhaps it would be possible to change the owner of /var/www to www-data directly ? Or maybe a better solution you might think of.

**Comment by ajardin** [comment]
That's a bit weird as you should not have an issue with Composer cache directory since https://github.com/origamiphp/docker-images/pull/82. Could you check that you are using the latest image on your local?

**Comment by Fulmenef** [comment]
Ok so we were missing the volume in the docker-compose.yml, thanks !
